-- ═══════════════════════════════════════════════════════════════
--  INTEGRUM ENERGY — Multi-Tenant Renewable Energy Platform
--  Schema Version: 1.0
--  Supports: Solar-only · Wind-only · Hybrid (Solar + Wind)
--  Extensible: Add any future energy source without DDL changes
-- ═══════════════════════════════════════════════════════════════

-- ──────────────────────────────────────────────────────────────
--  LAYER 1: LOOKUP / REFERENCE TABLES
-- ──────────────────────────────────────────────────────────────

-- All supported energy source types.
-- Adding a new source (e.g. HYDRO) = one INSERT, zero DDL changes.
CREATE TABLE energy_source_types (
    source_type_id   SERIAL          PRIMARY KEY,
    code             VARCHAR(30)     NOT NULL UNIQUE,   -- 'SOLAR', 'WIND', 'HYDRO', ...
    name             VARCHAR(100)    NOT NULL,
    unit             VARCHAR(20)     NOT NULL DEFAULT 'kWh',
    description      TEXT,
    is_active        BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- Seed values
INSERT INTO energy_source_types (code, name, unit, description) VALUES
    ('SOLAR', 'Solar Photovoltaic', 'kWh', 'Energy generated by solar PV panels'),
    ('WIND',  'Wind Turbine',       'kWh', 'Energy generated by wind turbine generators');
-- Note: HYBRID is not a separate source type.
-- A plant is Hybrid when it has both a SOLAR and a WIND row in plant_energy_sources.

-- TOD (Time-of-Day) tariff slot definitions — state-agnostic lookup
CREATE TABLE tod_slots (
    slot_id      SERIAL          PRIMARY KEY,
    slot_code    VARCHAR(10)     NOT NULL UNIQUE,   -- 'A','B','C','D' or 'PEAK','OFF_PEAK','NORMAL'
    slot_name    VARCHAR(60)     NOT NULL,
    start_time   TIME,
    end_time     TIME,
    description  TEXT,
    created_at   TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

INSERT INTO tod_slots (slot_code, slot_name, start_time, end_time, description) VALUES
    ('A',        'Night Off-Peak',  '22:00', '06:00', 'Lowest tariff band, overnight'),
    ('B',        'Morning',         '06:00', '09:00', 'Morning ramp-up period'),
    ('C',        'Day Normal',      '09:00', '18:00', 'Standard daytime tariff'),
    ('D',        'Evening Peak',    '18:00', '22:00', 'Highest tariff band, evening peak'),
    ('NORMAL',   'Normal',          '09:00', '18:00', 'MSEDCL normal slot'),
    ('OFF_PEAK', 'Off-Peak',        '22:00', '06:00', 'MSEDCL off-peak slot'),
    ('PEAK',     'Peak',            '06:00', '09:00', 'MSEDCL peak slot');


-- ──────────────────────────────────────────────────────────────
--  LAYER 2: TENANT (CUSTOMER) MANAGEMENT
-- ──────────────────────────────────────────────────────────────

-- One row per customer organisation. Root of all multi-tenancy.
CREATE TABLE tenants (
    tenant_id        SERIAL          PRIMARY KEY,
    tenant_code      VARCHAR(30)     NOT NULL UNIQUE,   -- short slug, e.g. 'GIL', 'C9'
    name             VARCHAR(200)    NOT NULL,
    org_type         VARCHAR(50),                       -- 'INDUSTRIAL', 'COMMERCIAL', 'CAPTIVE'
    state            VARCHAR(100),
    discom           VARCHAR(100),                      -- e.g. 'MSEDCL', 'BESCOM'
    gstin            VARCHAR(20),
    contact_email    VARCHAR(200),
    contact_phone    VARCHAR(20),
    is_active        BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- Users scoped to a tenant
CREATE TABLE users (
    user_id          SERIAL          PRIMARY KEY,
    tenant_id        INT             NOT NULL REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    username         VARCHAR(100)    NOT NULL,
    password_hash    VARCHAR(255)    NOT NULL,
    full_name        VARCHAR(200),
    email            VARCHAR(200),
    role             VARCHAR(30)     NOT NULL DEFAULT 'VIEWER',  -- 'ADMIN', 'ANALYST', 'VIEWER'
    is_active        BOOLEAN         NOT NULL DEFAULT TRUE,
    last_login_at    TIMESTAMPTZ,
    created_at       TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    UNIQUE (tenant_id, username),
    UNIQUE (tenant_id, email)
);


-- ──────────────────────────────────────────────────────────────
--  LAYER 3: PLANT & DEVICE HIERARCHY
-- ──────────────────────────────────────────────────────────────

-- Physical generation plants. A plant belongs to one tenant.
CREATE TABLE plants (
    plant_id             SERIAL          PRIMARY KEY,
    tenant_id            INT             NOT NULL REFERENCES tenants(tenant_id) ON DELETE CASCADE,
    plant_code           VARCHAR(50)     NOT NULL,
    plant_name           VARCHAR(200)    NOT NULL,
    location             VARCHAR(200),
    state                VARCHAR(100),
    latitude             DECIMAL(9,6),
    longitude            DECIMAL(9,6),
    total_capacity_mw    DECIMAL(10,3),
    commissioning_date   DATE,
    status               VARCHAR(30)     NOT NULL DEFAULT 'ACTIVE',  -- ACTIVE, INACTIVE, MAINTENANCE
    created_at           TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    UNIQUE (tenant_id, plant_code)
);

-- ┌─────────────────────────────────────────────────────────────┐
-- │  KEY DESIGN: Many-to-many between plants and energy sources │
-- │  Solar-only  → 1 row (SOLAR)                               │
-- │  Wind-only   → 1 row (WIND)                                │
-- │  Hybrid      → 2 rows (SOLAR + WIND)                       │
-- │  Future      → just INSERT a new energy_source_types row   │
-- └─────────────────────────────────────────────────────────────┘
CREATE TABLE plant_energy_sources (
    plant_source_id      SERIAL          PRIMARY KEY,
    plant_id             INT             NOT NULL REFERENCES plants(plant_id) ON DELETE CASCADE,
    source_type_id       INT             NOT NULL REFERENCES energy_source_types(source_type_id),
    installed_capacity_mw DECIMAL(10,3)  NOT NULL,
    commissioned_date    DATE,
    is_active            BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at           TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    UNIQUE (plant_id, source_type_id)
);

-- Individual generation units: solar panels, wind turbines, inverters, etc.
CREATE TABLE devices (
    device_id            SERIAL          PRIMARY KEY,
    plant_id             INT             NOT NULL REFERENCES plants(plant_id) ON DELETE CASCADE,
    source_type_id       INT             NOT NULL REFERENCES energy_source_types(source_type_id),
    serial_number        VARCHAR(100)    NOT NULL,
    device_name          VARCHAR(200),
    device_model         VARCHAR(200),
    manufacturer         VARCHAR(200),
    capacity_kw          DECIMAL(10,3),
    status               VARCHAR(30)     NOT NULL DEFAULT 'ACTIVE',
    installed_at         DATE,
    decommissioned_at    DATE,
    created_at           TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    UNIQUE (plant_id, serial_number)
);


-- ──────────────────────────────────────────────────────────────
--  LAYER 4: GENERATION TIME-SERIES (15-MIN)
-- ──────────────────────────────────────────────────────────────

-- One row per device per 15-minute interval.
-- source_type_id makes solar and wind readings queryable in a
-- single table — no separate solar_generation / wind_generation tables.
CREATE TABLE generation_readings (
    reading_id               BIGSERIAL       PRIMARY KEY,
    tenant_id                INT             NOT NULL REFERENCES tenants(tenant_id),
    plant_id                 INT             NOT NULL REFERENCES plants(plant_id),
    device_id                INT             NOT NULL REFERENCES devices(device_id),
    source_type_id           INT             NOT NULL REFERENCES energy_source_types(source_type_id),
    reading_date             DATE            NOT NULL,
    reading_time             TIME            NOT NULL,   -- start of 15-min slot
    generation_value         DECIMAL(14,4)   NOT NULL DEFAULT 0,  -- net after losses (kWh)
    generation_before_losses DECIMAL(14,4)   NOT NULL DEFAULT 0,  -- gross (kWh)
    created_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW()
) PARTITION BY RANGE (reading_date);

-- Monthly partitions for performance (extend as needed)
CREATE TABLE generation_readings_2025_04 PARTITION OF generation_readings
    FOR VALUES FROM ('2025-04-01') TO ('2025-05-01');
CREATE TABLE generation_readings_2025_05 PARTITION OF generation_readings
    FOR VALUES FROM ('2025-05-01') TO ('2025-06-01');
CREATE TABLE generation_readings_2025_06 PARTITION OF generation_readings
    FOR VALUES FROM ('2025-06-01') TO ('2025-07-01');
-- Add future partitions via: CREATE TABLE generation_readings_YYYY_MM PARTITION OF ...


-- ──────────────────────────────────────────────────────────────
--  LAYER 5: CONSUMPTION TIME-SERIES (15-MIN)
-- ──────────────────────────────────────────────────────────────

CREATE TABLE consumption_readings (
    consumption_id       BIGSERIAL       PRIMARY KEY,
    tenant_id            INT             NOT NULL REFERENCES tenants(tenant_id),
    plant_id             INT             NOT NULL REFERENCES plants(plant_id),
    reading_date         DATE            NOT NULL,
    reading_time         TIME            NOT NULL,
    tod_slot_id          INT             REFERENCES tod_slots(slot_id),
    consumption_value    DECIMAL(14,4)   NOT NULL DEFAULT 0,  -- kWh
    created_at           TIMESTAMPTZ     NOT NULL DEFAULT NOW()
) PARTITION BY RANGE (reading_date);

CREATE TABLE consumption_readings_2025_04 PARTITION OF consumption_readings
    FOR VALUES FROM ('2025-04-01') TO ('2025-05-01');
CREATE TABLE consumption_readings_2025_05 PARTITION OF consumption_readings
    FOR VALUES FROM ('2025-05-01') TO ('2025-06-01');
CREATE TABLE consumption_readings_2025_06 PARTITION OF consumption_readings
    FOR VALUES FROM ('2025-06-01') TO ('2025-07-01');


-- ──────────────────────────────────────────────────────────────
--  LAYER 6: SETTLEMENT & MATCHING (15-MIN)
-- ──────────────────────────────────────────────────────────────

-- How each device's generation is matched to consumption each slot.
CREATE TABLE settlement_matching (
    matching_id              BIGSERIAL       PRIMARY KEY,
    tenant_id                INT             NOT NULL REFERENCES tenants(tenant_id),
    plant_id                 INT             NOT NULL REFERENCES plants(plant_id),
    device_id                INT             NOT NULL REFERENCES devices(device_id),
    source_type_id           INT             NOT NULL REFERENCES energy_source_types(source_type_id),
    settlement_date          DATE            NOT NULL,
    settlement_time          TIME            NOT NULL,
    tod_slot_id              INT             REFERENCES tod_slots(slot_id),
    generation_value         DECIMAL(14,4)   NOT NULL DEFAULT 0,
    generation_before_losses DECIMAL(14,4)   NOT NULL DEFAULT 0,
    slot_total_consumption   DECIMAL(14,4)   NOT NULL DEFAULT 0,
    allocated_consumption    DECIMAL(14,4)   NOT NULL DEFAULT 0,
    surplus_generation       DECIMAL(14,4)   NOT NULL DEFAULT 0,
    surplus_gen_with_banking DECIMAL(14,4)   NOT NULL DEFAULT 0,
    matched_settlement       DECIMAL(14,4)   NOT NULL DEFAULT 0,
    created_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW()
) PARTITION BY RANGE (settlement_date);

CREATE TABLE settlement_matching_2025_04 PARTITION OF settlement_matching
    FOR VALUES FROM ('2025-04-01') TO ('2025-05-01');
CREATE TABLE settlement_matching_2025_05 PARTITION OF settlement_matching
    FOR VALUES FROM ('2025-05-01') TO ('2025-06-01');

-- 15-min slot aggregate (all devices combined)
CREATE TABLE slot_summary (
    slot_summary_id          BIGSERIAL       PRIMARY KEY,
    tenant_id                INT             NOT NULL REFERENCES tenants(tenant_id),
    plant_id                 INT             NOT NULL REFERENCES plants(plant_id),
    summary_date             DATE            NOT NULL,
    summary_time             TIME            NOT NULL,
    tod_slot_id              INT             REFERENCES tod_slots(slot_id),
    generation_value         DECIMAL(14,4)   NOT NULL DEFAULT 0,  -- combined all sources
    slot_total_consumption   DECIMAL(14,4)   NOT NULL DEFAULT 0,
    allocated_consumption    DECIMAL(14,4)   NOT NULL DEFAULT 0,
    surplus_generation       DECIMAL(14,4)   NOT NULL DEFAULT 0,
    surplus_gen_with_banking DECIMAL(14,4)   NOT NULL DEFAULT 0,
    matched_settlement       DECIMAL(14,4)   NOT NULL DEFAULT 0,
    created_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);


-- ──────────────────────────────────────────────────────────────
--  LAYER 7: DAILY & MONTHLY ROLL-UPS
-- ──────────────────────────────────────────────────────────────

-- Daily TOD slot summary
CREATE TABLE tod_daily_summary (
    tod_daily_id                 SERIAL          PRIMARY KEY,
    tenant_id                    INT             NOT NULL REFERENCES tenants(tenant_id),
    plant_id                     INT             NOT NULL REFERENCES plants(plant_id),
    summary_date                 DATE            NOT NULL,
    tod_slot_id                  INT             NOT NULL REFERENCES tod_slots(slot_id),
    generation_value             DECIMAL(14,4)   NOT NULL DEFAULT 0,
    slot_total_consumption       DECIMAL(14,4)   NOT NULL DEFAULT 0,
    allocated_consumption        DECIMAL(14,4)   NOT NULL DEFAULT 0,
    matched_settlement           DECIMAL(14,4)   NOT NULL DEFAULT 0,
    surplus_demand               DECIMAL(14,4)   NOT NULL DEFAULT 0,
    surplus_generation           DECIMAL(14,4)   NOT NULL DEFAULT 0,
    surplus_gen_with_banking     DECIMAL(14,4)   NOT NULL DEFAULT 0,
    matched_settlement_daily_tod DECIMAL(14,4)   NOT NULL DEFAULT 0,
    surplus_gen_daily_tod        DECIMAL(14,4)   NOT NULL DEFAULT 0,
    surplus_demand_daily_tod     DECIMAL(14,4)   NOT NULL DEFAULT 0,
    created_at                   TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    UNIQUE (tenant_id, plant_id, summary_date, tod_slot_id)
);

-- Monthly TOD banking settlement
CREATE TABLE monthly_banking_settlement (
    banking_id                       SERIAL          PRIMARY KEY,
    tenant_id                        INT             NOT NULL REFERENCES tenants(tenant_id),
    plant_id                         INT             NOT NULL REFERENCES plants(plant_id),
    settlement_month                 DATE            NOT NULL,  -- first day of month
    tod_slot_id                      INT             NOT NULL REFERENCES tod_slots(slot_id),
    generation_value                 DECIMAL(14,4)   NOT NULL DEFAULT 0,
    allocated_consumption            DECIMAL(14,4)   NOT NULL DEFAULT 0,
    matched_settlement               DECIMAL(14,4)   NOT NULL DEFAULT 0,
    surplus_demand                   DECIMAL(14,4)   NOT NULL DEFAULT 0,
    surplus_generation               DECIMAL(14,4)   NOT NULL DEFAULT 0,
    surplus_gen_with_banking         DECIMAL(14,4)   NOT NULL DEFAULT 0,
    slot_total_consumption           DECIMAL(14,4)   NOT NULL DEFAULT 0,
    matched_settlement_daily_tod     DECIMAL(14,4)   NOT NULL DEFAULT 0,
    surplus_gen_daily_tod            DECIMAL(14,4)   NOT NULL DEFAULT 0,
    surplus_demand_daily_tod         DECIMAL(14,4)   NOT NULL DEFAULT 0,
    matched_settlement_intra_monthly DECIMAL(14,4)   NOT NULL DEFAULT 0,
    surplus_gen_intra_monthly        DECIMAL(14,4)   NOT NULL DEFAULT 0,
    surplus_demand_intra_monthly     DECIMAL(14,4)   NOT NULL DEFAULT 0,
    created_at                       TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    UNIQUE (tenant_id, plant_id, settlement_month, tod_slot_id)
);

-- Monthly savings summary
CREATE TABLE savings_summary (
    savings_id                  SERIAL          PRIMARY KEY,
    tenant_id                   INT             NOT NULL REFERENCES tenants(tenant_id),
    plant_id                    INT             NOT NULL REFERENCES plants(plant_id),
    settlement_month            DATE            NOT NULL,
    total_consumption           DECIMAL(14,4)   NOT NULL DEFAULT 0,
    grid_cost                   DECIMAL(14,4)   NOT NULL DEFAULT 0,
    actual_cost_with_banking    DECIMAL(14,4)   NOT NULL DEFAULT 0,
    savings_with_banking        DECIMAL(14,4)   NOT NULL DEFAULT 0,
    savings_pct_with_banking    DECIMAL(7,4)    NOT NULL DEFAULT 0,
    actual_cost_without_banking DECIMAL(14,4)   NOT NULL DEFAULT 0,
    savings_without_banking     DECIMAL(14,4)   NOT NULL DEFAULT 0,
    savings_pct_without_banking DECIMAL(7,4)    NOT NULL DEFAULT 0,
    created_at                  TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    UNIQUE (tenant_id, plant_id, settlement_month)
);


-- ──────────────────────────────────────────────────────────────
--  LAYER 8: TARIFFS & BILLING
-- ──────────────────────────────────────────────────────────────

-- TOD tariff rates per tenant per month per slot
CREATE TABLE tariff_config (
    tariff_id        SERIAL          PRIMARY KEY,
    tenant_id        INT             NOT NULL REFERENCES tenants(tenant_id),
    effective_month  DATE            NOT NULL,   -- first day of month
    tod_slot_id      INT             NOT NULL REFERENCES tod_slots(slot_id),
    rate_per_kwh     DECIMAL(8,4)    NOT NULL,
    discom           VARCHAR(100),
    state            VARCHAR(100),
    created_at       TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    UNIQUE (tenant_id, effective_month, tod_slot_id)
);

-- Grid cost bill breakdown per tenant per month
CREATE TABLE grid_cost_components (
    cost_id                  SERIAL          PRIMARY KEY,
    tenant_id                INT             NOT NULL REFERENCES tenants(tenant_id),
    plant_id                 INT             NOT NULL REFERENCES plants(plant_id),
    month                    DATE            NOT NULL,
    demand_charges           DECIMAL(14,4)   NOT NULL DEFAULT 0,
    energy_charges           DECIMAL(14,4)   NOT NULL DEFAULT 0,
    wheeling_charges         DECIMAL(14,4)   NOT NULL DEFAULT 0,
    tod_tariff_charges       DECIMAL(14,4)   NOT NULL DEFAULT 0,
    fuel_cost_adjustment     DECIMAL(14,4)   NOT NULL DEFAULT 0,
    electricity_duty         DECIMAL(14,4)   NOT NULL DEFAULT 0,
    tax_on_sale              DECIMAL(14,4)   NOT NULL DEFAULT 0,
    bulk_discount            DECIMAL(14,4)   NOT NULL DEFAULT 0,
    incremental_rebate       DECIMAL(14,4)   NOT NULL DEFAULT 0,
    prompt_payment_discount  DECIMAL(14,4)   NOT NULL DEFAULT 0,
    gom_subsidy              DECIMAL(14,4)   NOT NULL DEFAULT 0,
    other_adjustments        DECIMAL(14,4)   NOT NULL DEFAULT 0,
    total_grid_bill          DECIMAL(14,4)   NOT NULL DEFAULT 0,
    created_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    UNIQUE (tenant_id, plant_id, month)
);

-- RE plant cost breakdown per energy source per month
CREATE TABLE re_cost_components (
    re_cost_id               SERIAL          PRIMARY KEY,
    tenant_id                INT             NOT NULL REFERENCES tenants(tenant_id),
    plant_id                 INT             NOT NULL REFERENCES plants(plant_id),
    source_type_id           INT             NOT NULL REFERENCES energy_source_types(source_type_id),
    month                    DATE            NOT NULL,
    om_charges               DECIMAL(14,4)   NOT NULL DEFAULT 0,
    transmission_charges     DECIMAL(14,4)   NOT NULL DEFAULT 0,
    wheeling_charges         DECIMAL(14,4)   NOT NULL DEFAULT 0,
    scheduling_charges       DECIMAL(14,4)   NOT NULL DEFAULT 0,
    deviation_charges        DECIMAL(14,4)   NOT NULL DEFAULT 0,
    asset_management_charges DECIMAL(14,4)   NOT NULL DEFAULT 0,
    oa_application_charges   DECIMAL(14,4)   NOT NULL DEFAULT 0,
    startup_power_bill       DECIMAL(14,4)   NOT NULL DEFAULT 0,
    gst_reversal             DECIMAL(14,4)   NOT NULL DEFAULT 0,
    depreciation             DECIMAL(14,4)   NOT NULL DEFAULT 0,
    overheads                DECIMAL(14,4)   NOT NULL DEFAULT 0,
    total_re_cost            DECIMAL(14,4)   NOT NULL DEFAULT 0,
    created_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    UNIQUE (tenant_id, plant_id, source_type_id, month)
);

-- DISCOM bill line items (for C9-style wheeling customers)
CREATE TABLE discom_bills (
    bill_id                  SERIAL          PRIMARY KEY,
    tenant_id                INT             NOT NULL REFERENCES tenants(tenant_id),
    plant_id                 INT             NOT NULL REFERENCES plants(plant_id),
    month                    DATE            NOT NULL,
    bill_header              VARCHAR(200),
    tariff_rate              DECIMAL(8,4),
    total_consumption        DECIMAL(14,4)   NOT NULL DEFAULT 0,
    cost_without_re          DECIMAL(14,4)   NOT NULL DEFAULT 0,
    cost_with_re_wheeling    DECIMAL(14,4)   NOT NULL DEFAULT 0,
    discom_bill_amount       DECIMAL(14,4)   NOT NULL DEFAULT 0,
    savings                  DECIMAL(14,4)   NOT NULL DEFAULT 0,
    created_at               TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

-- Effective rate summary per plant per month
CREATE TABLE effective_rate_summary (
    rate_id                    SERIAL          PRIMARY KEY,
    tenant_id                  INT             NOT NULL REFERENCES tenants(tenant_id),
    plant_id                   INT             NOT NULL REFERENCES plants(plant_id),
    billing_month              DATE            NOT NULL,
    total_units_consumed       DECIMAL(14,4)   NOT NULL DEFAULT 0,
    total_electricity_bill     DECIMAL(14,4)   NOT NULL DEFAULT 0,
    total_demand_charges       DECIMAL(14,4)   NOT NULL DEFAULT 0,
    effective_rate             DECIMAL(8,4)    NOT NULL DEFAULT 0,
    effective_rate_excl_demand DECIMAL(8,4)    NOT NULL DEFAULT 0,
    created_at                 TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    UNIQUE (tenant_id, plant_id, billing_month)
);


-- ──────────────────────────────────────────────────────────────
--  LAYER 9: PERFORMANCE METRICS (ANNUAL)
-- ──────────────────────────────────────────────────────────────

-- Annual performance per plant per energy source
CREATE TABLE performance_metrics (
    metric_id                                    SERIAL          PRIMARY KEY,
    tenant_id                                    INT             NOT NULL REFERENCES tenants(tenant_id),
    plant_id                                     INT             NOT NULL REFERENCES plants(plant_id),
    source_type_id                               INT             NOT NULL REFERENCES energy_source_types(source_type_id),
    financial_year                               VARCHAR(10)     NOT NULL,  -- '2025-2026'
    generation_total                             DECIMAL(16,4)   NOT NULL DEFAULT 0,
    plf_percent                                  DECIMAL(7,4)    NOT NULL DEFAULT 0,
    realised_kwh_captive_consumption             DECIMAL(16,4)   NOT NULL DEFAULT 0,
    sale_of_energy                               DECIMAL(16,4)   NOT NULL DEFAULT 0,
    over_injection                               DECIMAL(16,4)   NOT NULL DEFAULT 0,
    total_plant_consumption                      DECIMAL(16,4)   NOT NULL DEFAULT 0,
    total_re_consumption_capex                   DECIMAL(16,4)   NOT NULL DEFAULT 0,
    re_percent_capex                             DECIMAL(7,4)    NOT NULL DEFAULT 0,
    total_re_consumption_tpa                     DECIMAL(16,4)   NOT NULL DEFAULT 0,
    re_percent_tpa                               DECIMAL(7,4)    NOT NULL DEFAULT 0,
    total_re_percent                             DECIMAL(7,4)    NOT NULL DEFAULT 0,
    actual_losses                                DECIMAL(16,4)   NOT NULL DEFAULT 0,
    losses_excl_over_injection                   DECIMAL(16,4)   NOT NULL DEFAULT 0,
    losses_excl_over_injection_percent           DECIMAL(7,4)    NOT NULL DEFAULT 0,
    banking_loss_percent                         DECIMAL(7,4)    NOT NULL DEFAULT 0,
    created_at                                   TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    UNIQUE (tenant_id, plant_id, source_type_id, financial_year)
);

-- Per-device annual metrics (e.g., per wind turbine, per solar string)
CREATE TABLE device_yearly_metrics (
    device_metric_id    SERIAL          PRIMARY KEY,
    tenant_id           INT             NOT NULL REFERENCES tenants(tenant_id),
    plant_id            INT             NOT NULL REFERENCES plants(plant_id),
    device_id           INT             NOT NULL REFERENCES devices(device_id),
    source_type_id      INT             NOT NULL REFERENCES energy_source_types(source_type_id),
    financial_year      VARCHAR(10)     NOT NULL,
    generation_total    DECIMAL(16,4)   NOT NULL DEFAULT 0,
    plf_percent         DECIMAL(7,4),
    availability_pct    DECIMAL(7,4),
    created_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    UNIQUE (device_id, financial_year)
);


-- ──────────────────────────────────────────────────────────────
--  LAYER 10: AI CHAT HISTORY
-- ──────────────────────────────────────────────────────────────

CREATE TABLE chat_threads (
    thread_id    SERIAL          PRIMARY KEY,
    tenant_id    INT             NOT NULL REFERENCES tenants(tenant_id),
    user_id      INT             REFERENCES users(user_id),
    title        VARCHAR(300),
    created_at   TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

CREATE TABLE chat_history (
    message_id   BIGSERIAL       PRIMARY KEY,
    thread_id    INT             NOT NULL REFERENCES chat_threads(thread_id) ON DELETE CASCADE,
    tenant_id    INT             NOT NULL REFERENCES tenants(tenant_id),
    role         VARCHAR(20)     NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
    content      TEXT            NOT NULL,
    created_at   TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);


-- ══════════════════════════════════════════════════════════════
--  INDEXES
-- ══════════════════════════════════════════════════════════════

-- Tenant scoping (most queries filter by tenant first)
CREATE INDEX idx_plants_tenant                  ON plants(tenant_id);
CREATE INDEX idx_users_tenant                   ON users(tenant_id);
CREATE INDEX idx_devices_plant                  ON devices(plant_id);
CREATE INDEX idx_plant_energy_sources_plant     ON plant_energy_sources(plant_id);
CREATE INDEX idx_plant_energy_sources_type      ON plant_energy_sources(source_type_id);

-- Time-series (date + tenant is the most common filter combo)
CREATE INDEX idx_gen_readings_tenant_date       ON generation_readings(tenant_id, reading_date);
CREATE INDEX idx_gen_readings_device_date       ON generation_readings(device_id, reading_date);
CREATE INDEX idx_gen_readings_source_date       ON generation_readings(source_type_id, reading_date);
CREATE INDEX idx_cons_readings_tenant_date      ON consumption_readings(tenant_id, reading_date);
CREATE INDEX idx_settlement_tenant_date         ON settlement_matching(tenant_id, settlement_date);
CREATE INDEX idx_slot_summary_tenant_date       ON slot_summary(tenant_id, summary_date);

-- Monthly roll-ups
CREATE INDEX idx_banking_tenant_month           ON monthly_banking_settlement(tenant_id, settlement_month);
CREATE INDEX idx_savings_tenant_month           ON savings_summary(tenant_id, settlement_month);
CREATE INDEX idx_perf_metrics_tenant_year       ON performance_metrics(tenant_id, financial_year);

-- Chat
CREATE INDEX idx_chat_history_thread            ON chat_history(thread_id);
CREATE INDEX idx_chat_threads_tenant            ON chat_threads(tenant_id);


-- ══════════════════════════════════════════════════════════════
--  VIEWS
-- ══════════════════════════════════════════════════════════════

-- Unified generation view: merges all energy sources in one place
CREATE VIEW v_generation_by_source AS
SELECT
    gr.tenant_id,
    t.name                      AS tenant_name,
    gr.plant_id,
    p.plant_name,
    p.state,
    est.code                    AS source_type,
    d.serial_number,
    gr.reading_date,
    gr.reading_time,
    gr.generation_value,
    gr.generation_before_losses,
    (gr.generation_before_losses - gr.generation_value) AS transmission_loss
FROM generation_readings       gr
JOIN tenants                   t   ON t.tenant_id    = gr.tenant_id
JOIN plants                    p   ON p.plant_id     = gr.plant_id
JOIN devices                   d   ON d.device_id    = gr.device_id
JOIN energy_source_types       est ON est.source_type_id = gr.source_type_id;

-- Plant capability view: shows what each plant can generate
CREATE VIEW v_plant_capabilities AS
SELECT
    p.plant_id,
    p.tenant_id,
    t.name                              AS tenant_name,
    t.tenant_code,
    p.plant_name,
    p.location,
    p.state,
    p.total_capacity_mw,
    STRING_AGG(est.code, ' + ' ORDER BY est.code) AS energy_sources,
    BOOL_OR(est.code = 'SOLAR')         AS has_solar,
    BOOL_OR(est.code = 'WIND')          AS has_wind,
    COUNT(DISTINCT pes.source_type_id)  AS source_count,
    SUM(pes.installed_capacity_mw)      AS total_installed_mw
FROM plants                p
JOIN tenants               t   ON t.tenant_id    = p.tenant_id
JOIN plant_energy_sources  pes ON pes.plant_id   = p.plant_id
JOIN energy_source_types   est ON est.source_type_id = pes.source_type_id
WHERE pes.is_active = TRUE
GROUP BY p.plant_id, p.tenant_id, t.name, t.tenant_code, p.plant_name,
         p.location, p.state, p.total_capacity_mw;

-- Monthly generation summary per plant per source
CREATE VIEW v_monthly_generation AS
SELECT
    tenant_id,
    plant_id,
    source_type_id,
    DATE_TRUNC('month', reading_date)   AS month,
    SUM(generation_value)               AS total_generation_kwh,
    SUM(generation_before_losses)       AS gross_generation_kwh,
    SUM(generation_before_losses - generation_value) AS total_losses_kwh,
    COUNT(DISTINCT reading_date)        AS days_with_data
FROM generation_readings
GROUP BY tenant_id, plant_id, source_type_id, DATE_TRUNC('month', reading_date);


-- ══════════════════════════════════════════════════════════════
--  SAMPLE DATA — demonstrates all three scenarios
-- ══════════════════════════════════════════════════════════════

-- Tenant 1: Cloud9 — Solar Only
INSERT INTO tenants (tenant_code, name, org_type, state, discom)
VALUES ('C9', 'Cloud9', 'COMMERCIAL', 'Karnataka', 'BESCOM');

-- Tenant 2: GIL — Hybrid (Wind + Solar)
INSERT INTO tenants (tenant_code, name, org_type, state, discom)
VALUES ('GIL', 'Graphite India Limited', 'INDUSTRIAL', 'Maharashtra', 'MSEDCL');

-- Tenant 3: Future — Wind Only
INSERT INTO tenants (tenant_code, name, org_type, state, discom)
VALUES ('ACME_WIND', 'Acme Wind Power Ltd', 'INDUSTRIAL', 'Rajasthan', 'RVPN');

-- Plants
INSERT INTO plants (tenant_id, plant_code, plant_name, location, state, total_capacity_mw)
VALUES
    (1, 'C9-BLR-01', 'Bengaluru Solar Fleet', 'Bengaluru', 'Karnataka', 2.50),
    (2, 'GIL-MH-01',  'GIL Hybrid Plant',      'Nagpur',    'Maharashtra', 5.00),
    (3, 'ACME-RJ-01', 'Acme Wind Farm',         'Jaisalmer', 'Rajasthan', 10.00);

-- Plant energy sources — the pivot of the design
INSERT INTO plant_energy_sources (plant_id, source_type_id, installed_capacity_mw) VALUES
    (1, 1, 2.50),   -- C9: SOLAR only
    (2, 1, 2.00),   -- GIL: SOLAR (2 MW)
    (2, 2, 3.00),   -- GIL: WIND  (3 MW) → HYBRID
    (3, 2, 10.00);  -- ACME: WIND only
